import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';

export default function TermsPage() {
  const today = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <main className="min-h-screen bg-white">
      <Navbar />

      <section className="container mx-auto px-4 py-20 max-w-4xl">
        {/* Page Title */}
        <div className="text-center mb-14">
          <h1 className="text-4xl font-semibold text-gray-900">
            Terms & Conditions
          </h1>
          <div className="w-14 h-1 bg-green-600 mx-auto mt-4" />
          <p className="mt-6 text-sm text-gray-500">
            Last updated on {today}
          </p>
        </div>

        {/* Content */}
        <div className="space-y-10 text-gray-700 leading-relaxed text-base">
          <section>
            <p>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and the rules made thereunder, as amended. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>
            <p className="mt-3">
              This document is published in accordance with Rule 3 (1) of the
              Information Technology (Intermediaries Guidelines) Rules, 2011 for
              access or usage of the website https://www.bigbrosai.com
              ("Platform").
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              1. Platform Ownership
            </h2>
            <p>
              The Platform is owned by BIGBROS AI PRIVATE LIMITED, a company
              incorporated under the Companies Act, 1956, having its registered
              office at E-93, Govind Nagar, Near Shiv Park, Mathura, Uttar
              Pradesh, India (the “Platform Owner”, “we”, “us”, “our”).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              2. Acceptance of Terms
            </h2>
            <p>
              Your access, browsing, or use of the Platform indicates your
              agreement to all the Terms and Conditions contained herein. If you
              do not agree, please do not use the Platform.
            </p>
            <p className="mt-3">
              Any additional or conflicting terms proposed by you are expressly
              rejected and shall be of no force or effect.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              3. User Definition
            </h2>
            <p>
              For the purpose of these Terms, “you”, “your”, or “user” shall mean
              any natural or legal person who has agreed to become a user of the
              Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              4. User Obligations
            </h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                You agree to provide true, accurate, and complete information
                during registration and thereafter.
              </li>
              <li>
                You shall be responsible for all activities conducted through
                your registered account.
              </li>
              <li>
                You agree to comply with all applicable Indian and local laws.
              </li>
              <li>
                You agree not to use the Platform or Services for any unlawful,
                illegal, or prohibited purpose.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              5. No Warranties
            </h2>
            <p>
              The Platform and Services are provided on an “as is” basis. Neither
              we nor any third party provides any warranty regarding accuracy,
              performance, completeness, or suitability of the content.
            </p>
            <p className="mt-3">
              Your use of the Platform and Services is entirely at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              6. Intellectual Property
            </h2>
            <p>
              All content on the Platform including text, design, layout,
              graphics, and software is proprietary to us. You shall not claim
              any intellectual property rights over such content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              7. Third-Party Links
            </h2>
            <p>
              The Platform may contain links to third-party websites. Accessing
              such links will be governed by the respective terms and privacy
              policies of those websites. We are not responsible for their
              content or practices.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              8. Payments
            </h2>
            <p>
              You agree to pay all charges associated with availing the Services
              as communicated on the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              9. Indemnification
            </h2>
            <p>
              You agree to indemnify and hold harmless the Platform Owner and its
              affiliates from any claim, demand, or penalty arising out of your
              breach of these Terms or violation of applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              10. Force Majeure
            </h2>
            <p>
              Neither party shall be liable for failure or delay in performance
              due to events beyond reasonable control.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              11. Governing Law & Jurisdiction
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with
              the laws of India. All disputes shall be subject to the exclusive
              jurisdiction of the courts of Mathura, Uttar Pradesh.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-3">
              12. Contact
            </h2>
            <p>
              All concerns or communications relating to these Terms must be sent
              using the contact information provided on this Platform.
            </p>
          </section>
        </div>
      </section>

      <Footer />
    </main>
  );
}
